#!/bin/sh

. /sbin/config.sh
. /sbin/global.sh

cons="  root root 622"
disk="  root root 660"
null="  root root 666"
urandom="  root root  644"
mkdev () {    # usage: mkdev name [bcu] major minor owner group mode
        if [ "$opt_v" ]
        then    if [ "$opt_d" ]
                then    echo "rm -f $1"
                else    echo "$1        = $2 $3 $4 $5:$6 $7"
                fi
        fi
        [ ! "$opt_n" ] && rm -f $1 &&
        [ ! "$opt_d" ] && mknod $1 $2 $3 $4 &&
                chmod $7 $1
}  
cd $1

mkdev	dev/ram	    b	1   1	$disk 
mkdev	dev/ram0    b	1   0	$disk
mkdev	dev/ram1    b	1   1	$disk 
mkdev	dev/ram2    b	1   2	$disk
mkdev	dev/ram3    b	1   3	$disk

mkdev	dev/mem     c	1   1	$disk
mkdev	dev/kmem    c	1   2	$null
mkdev	dev/null    c	1   3	$null
mkdev	dev/random  c	1   8	$urandom
mkdev	dev/urandom c   1   9   $urandom


mkdev	dev/ptyp0   c	2   0	$urandom
mkdev	dev/ptyp1   c	2   1	$urandom

mkdev	dev/ttyp0   c	3   0	$urandom
mkdev	dev/ttyp1   c	3   1	$urandom

mkdev	dev/ptmx    c	5   2	$null

mkdev	dev/ttyS0   c	4   64	$cons
mkdev	dev/ttyS1   c	4   65	$cons
mkdev	dev/console c   5   1   $cons

# for Option Icon 225 3G dongle
if [ "$CONFIG_USB_SERIAL_HSO" = "y" ] || [ "$CONFIG_USB_SERIAL_HSO" = "m" ]; then
	mkdev	dev/ttyHS0   c	245 0	$cons
	mkdev	dev/ttyHS1   c	245 1	$cons
	mkdev	dev/ttyHS2   c	245 2	$cons
	mkdev	dev/ttyHS3   c	245 3	$cons
fi

# for generic 3G dongle
if [ "$CONFIG_USB_SERIAL" = "y" ] || [ "$CONFIG_USB_SERIAL" = "m" ]; then
	mkdev	dev/ttyUSB0   c	188 0	$cons
	mkdev	dev/ttyUSB1   c	188 1	$cons
	mkdev	dev/ttyUSB2   c	188 2	$cons
	mkdev	dev/ttyUSB3   c	188 3	$cons
fi

# for BandLuxe 3G dongle
if [ "$CONFIG_BLK_DEV_SR" = "y" ] || [ "$CONFIG_BLK_DEV_SR" = "m" ]; then
mkdev	dev/sr0	    b	11  0	$cons
fi
if [ "$CONFIG_CHR_DEV_SG" = "y" ] || [ "$CONFIG_CHR_DEV_SG" = "m" ]; then
mkdev	dev/sg0	    c	21  0	$cons
fi

mkdev   dev/mtdblock0 b  31 0 $disk
mkdev   dev/mtdblock1 b  31 1 $disk
mkdev   dev/mtdblock2 b  31 2 $disk
mkdev   dev/mtdblock3 b  31 3 $disk
mkdev   dev/mtdblock4 b  31 4 $disk
mkdev   dev/mtdblock5 b  31 5 $disk
mkdev   dev/mtdblock6 b  31 6 $disk
mkdev   dev/mtdblock7 b  31 7 $disk
mkdev   dev/mtdblock8 b  31 8 $disk
mkdev   dev/mtdblock9 b  31 9 $disk
mkdev   dev/mtdblock10 b  31 10 $disk
mkdev   dev/mtdblock11 b  31 11 $disk
mkdev   dev/mtdblock12 b  31 12 $disk
mkdev   dev/mtdblock13 b  31 13 $disk
mkdev   dev/mtdblock14 b  31 14 $disk
mkdev   dev/mtdblock15 b  31 15 $disk
mkdev   dev/mtdblock16 b  31 16 $disk
mkdev   dev/mtdblock17 b  31 17 $disk
mkdev   dev/mtdblock18 b  31 18 $disk
mkdev   dev/mtdblock19 b  31 19 $disk
mkdev   dev/mtdblock20 b  31 20 $disk
mkdev   dev/mtdblock21 b  31 21 $disk
mkdev   dev/mtd0      c  90 0 $disk
mkdev   dev/mtd0ro    c  90 1 $disk
mkdev   dev/mtd1      c  90 2 $disk
mkdev   dev/mtd1ro    c  90 3 $disk
mkdev   dev/mtd2      c  90 4 $disk
mkdev   dev/mtd2ro    c  90 5 $disk
mkdev   dev/mtd3      c  90 6 $disk
mkdev   dev/mtd3ro    c  90 7 $disk
mkdev   dev/mtd4      c  90 8 $disk
mkdev   dev/mtd4ro    c  90 9 $disk
mkdev   dev/mtd5      c  90 10 $disk
mkdev   dev/mtd5ro    c  90 11 $disk
mkdev   dev/mtd6      c  90 12 $disk
mkdev   dev/mtd6ro    c  90 13 $disk
mkdev   dev/mtd7      c  90 14 $disk
mkdev   dev/mtd7ro    c  90 15 $disk
mkdev   dev/mtd8      c  90 16 $disk
mkdev   dev/mtd8ro    c  90 17 $disk
mkdev   dev/mtd9      c  90 18 $disk
mkdev   dev/mtd9ro    c  90 19 $disk
mkdev   dev/mtd10      c  90 20 $disk
mkdev   dev/mtd10ro    c  90 21 $disk
mkdev   dev/mtd11      c  90 22 $disk
mkdev   dev/mtd11ro    c  90 23 $disk
mkdev   dev/mtd12      c  90 24 $disk
mkdev   dev/mtd12ro    c  90 25 $disk
mkdev   dev/mtd13      c  90 26 $disk
mkdev   dev/mtd13ro    c  90 27 $disk
mkdev   dev/mtd14      c  90 28 $disk
mkdev   dev/mtd14ro    c  90 29 $disk
mkdev   dev/mtd15      c  90 30 $disk
mkdev   dev/mtd15ro    c  90 31 $disk
mkdev   dev/mtd16      c  90 32 $disk
mkdev   dev/mtd16ro    c  90 33 $disk
mkdev   dev/mtd17      c  90 34 $disk
mkdev   dev/mtd17ro    c  90 35 $disk
mkdev   dev/mtd18      c  90 36 $disk
mkdev   dev/mtd18ro    c  90 37 $disk
mkdev   dev/mtd19      c  90 38 $disk
mkdev   dev/mtd19ro    c  90 39 $disk

mkdev	dev/video0  c	81	0   $cons
mkdev	dev/ppp	    c	108	0   $cons
mkdev	dev/pts/0   c	136	0   $cons 
mkdev	dev/pts/1   c	136	1   $cons 
mkdev	dev/pts/2   c	136	2   $cons 
mkdev	dev/pts/3   c	136	3   $cons 
mkdev   dev/spiS0   c   217     0   $cons
mkdev   dev/i2cM0   c   218     0   $cons

mkdev	dev/flash0  c	200	0   $cons
mkdev	dev/swnat0  c	210	0   $cons
mkdev	dev/hwnat0  c	220	0   $cons

mkdev	dev/sc_led  c	225	0   $cons

mkdev	dev/acl0    c	230	0   $cons
mkdev	dev/ac0	    c	240	0   $cons
mkdev	dev/mtr0    c	250	0   $cons
mkdev   dev/nvram   c   251     0   $cons
mkdev	dev/gpio    c	252	0   $cons
mkdev	dev/rdm0    c	253	0   $cons
mkdev	dev/watchdog   c 10   130   $cons
mkdev   dev/pcm0        c 233   0       $cons
mkdev   dev/i2s0        c 234   0   $cons
mkdev	dev/cls0	c 235	0	$cons
