#!/bin/sh
#
# This script is called with the following parameters:
# interface tty speed local-address remote-address ipparam
#

/usr/sbin/echo ipv6 ppp DOWN script > /dev/console

DEVICE=$1

#/usr/sbin/rc ipv6 dhcp6c stop
#/usr/sbin/rc_app/rc_ipv6 restart
