#!/bin/sh
#
# This script is called with the following parameters:
# interface tty speed local-address remote-address ipparam
#

/usr/sbin/echo ipv6 ppp UP script > /dev/console

# Start router advertisements on this link.
# Based on radvd 0.5.0 behaviour

DEVICE=$1


/usr/sbin/echo ipv6 ppp UP script update accept_ra trigger_rs wan_if to proc > /dev/console
/usr/sbin/echo 2 > /proc/sys/net/ipv6/conf/$DEVICE/accept_ra
/usr/sbin/echo trigger_rs=1 > /proc/net/trigger_rs
/usr/sbin/echo wan_if=$DEVICE > /proc/net/trigger_rs


/usr/sbin/echo ipv6 ppp UP script call ipv6pppup restart > /dev/console
#/usr/sbin/rc ipv6 dhcp6c restart &
#EVG1500 only support 2 args
/usr/sbin/rc ipv6pppup restart &

/usr/sbin/echo ipv6 ppp UP script done > /dev/console

